default_language_version:
  python: python3.11
default_stages: [pre-commit, pre-push, prepare-commit-msg, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python imports sorter)
        language_version: python3.11

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
